modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/FriendlyEndermite/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="friendermite"
    logoFile="friendermite.png"
    version="1.0.6"
    displayName="Friendermite"
    displayURL="https://modrinth.com/mod/friendermite"
    authors="CreativeMD"
    description='''Endermans will not attack Endermites anymore, so they cannot be used to make an Enderman farm.'''

[[dependencies.friendermite]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.friendermite]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

